services:
  db:
    image: postgres:15
    container_name: tastybites_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: tastybites
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - tasty_net

  backend:
    build:
      context: ./backend
    container_name: tastybites_backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/tastybites
    networks:
      - tasty_net
    expose:
      - 8000

  frontend:
    build:
      context: ./frontend
    container_name: tastybites_frontend
    depends_on:
      - backend
    networks:
      - tasty_net

  nginx:
    image: nginx:1.28-alpine
    container_name: tastybites_nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    networks:
      - tasty_net

volumes:
  postgres_data:

networks:
  tasty_net:
