services:
  backend:
    build: ./backend     # path to your FastAPI Dockerfile
    depends_on:
      db:
        condition: service_healthy         # make sure the db service is started first
    environment:
      DATABASE_URL: postgresql://postgres:cos101@db:5432/fastapi
    ports:
      - "8000:8000" 

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    container_name: frontend
    depends_on:
      - backend
    expose:
      - 80

  nginx:
    image: nginx:1.28
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro


  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cos101
      POSTGRES_DB: fastapi
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
volumes:
  db_data: